const GAME_DURATION_SECONDS = 199;
const WARN_BEATS = 1;
const CLUTCH_BONUS = 15;
const N = 5, CELL = 60, GAP = 4, PAD = 6, PLAYER_PX = 6, UNI_PX = 5;
const GRID_W = PAD * 2 + N * CELL + (N - 1) * GAP;
const UNI_DOCK_LEFT = (GRID_W - UNI_BMP[0].length * UNI_PX) / 2;
const UNI_DOCK_TOP = -60;
const hud = document.getElementById('hud');
const gridEl = document.getElementById('grid');
const scoreEl = document.getElementById('score');
const timeValEl = document.getElementById('timeVal');
const heartsEl = document.getElementById('hearts');
const hudSongTitle = document.getElementById('hudSongTitle');
const msgEl = document.getElementById('msg');
const restartBtn = document.getElementById('restart');
const menuBtn = document.getElementById('menuBtn');
const unicornWrap = document.getElementById('unicornWrap');
const startOverlay = document.getElementById('startOverlay');
const startBtn = document.getElementById('startBtn');
const unicornCanvas = document.getElementById('unicornCanvas');
const DEFAULT_MSG = 'Arrow keys / WASD to move';

const D2 = -31, D3 = -19, E3 = -17, F3 = -16, G3 = -14, A3 = -12, BB3 = -11, C4 = -9, D4 = -7, E4 = -5, F4 = -4, FS4 = -3, G4 = -2, A4 = 0, BB4 = 1, B4 = 2, C5 = 3, CS5 = 4, D5 = 5, E5 = 7, F5 = 8, FS5 = 9, G5 = 10, A5 = 12, D6 = 17;
const BAR = 60 / 130 * 4;
const STEP_DUR = BAR / 16;

let cells = [];
let player = { r: 4, c: 2, facingLeft: false };
let lives = 3;
let score = 0;
let pending = [];
let running = false;
let gameStarted = false;
let introDone = false;
let timer = null;
let clockTimer = null;
let audioCtx = null;
let playerCanvas;
let uniFlyCanvas;
let startTime = 0;
let currentStageIdx = -1;
let stageBeatCounter = 0;
let canMove = true;

let STAGES = [];
let SECTIONS = [];